# docker-compose.yml
version: "3.8"

services:

  # Services
  pub:
    restart: always
    build:
      context: ../
      dockerfile: ./deployments/pub.Dockerfile
    depends_on:
      - nats-streaming
    networks:
      - common-net
    ports:
      - 50051:50051

  sub:
    restart: always
    build:
      context: ../
      dockerfile: ./deployments/sub.Dockerfile
    env_file: ../.env
    depends_on:
      - datastore
      - nats-streaming
    networks:
      - common-net
    ports:
      - 50052:50051

  # Nats streaming server
  nats-streaming:
    image: nats-streaming:alpine
    networks:
      - common-net
    expose:
      - 4222
    ports:
      - 8223:8223

  # Database tier
  datastore:
    image: postgres:14.5
    container_name: "datastore"
    restart: always
    environment:
      PGHOST: "datastore"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    networks:
      - common-net
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ../scripts/db.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  common-net: {}