# docker-compose.yml
version: "3.9"

services:

  # Services
  pub:
    restart: always
    build:
      context: .
      dockerfile: pub.Dockerfile
    networks:
      - default
    ports:
      - 50051:50051

  sub:
    restart: always
    build:
      context: .
      dockerfile: sub.Dockerfile
    env_file: .env
    depends_on:
      - subscriber
      - datastore
    networks:
      - default
    ports:
      - 50052:50051

  # Commands
  cli:
    build: ./shippy-cli-consignment

  # Database tier
  datastore:
    image: postgres
    container_name: "datastore"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

networks:
  postgres:
    driver: bridge